name: onefish
description: OneFish Mobile Application for World Fish
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.17.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    flutter_screenutil: ^5.0.1
    flutter_svg: ^1.1.1+1
    shared_preferences: ^2.0.15
    responsive_builder: ^0.4.2
    provider: ^6.0.3
    get_it: ^7.2.0
    equatable: ^2.0.3
    logging: ^1.0.2
    pinput: ^2.2.11
    animated_splash_screen: ^1.3.0
    connectivity_plus: ^2.1.0
    calendar_date_picker2: ^0.2.2
    jiffy: ^5.0.0
    dropdown_button2: ^1.7.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/login/
    - assets/images/images/
    - assets/images/dummy/
    - assets/icon/
    - assets/icon/bottomNav/
    - assets/icon/home/
  fonts:
    - family: Noto Sans Bengali
      fonts:
        - asset: assets/fonts/Noto_Sans_Bengali_Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages